targets:
  $default:
    builders:
      freezed:
        options:
          union_constructor: all
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false