name: Auto Release (Semantic)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'qwlong/dorval'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build
      run: yarn build
    
    - name: Run tests
      run: yarn test
    
    - name: Release with Semantic Release
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        # Configure npm authentication
        npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

        # Run semantic-release
        # This will:
        # 1. Analyze commits since last release
        # 2. Determine version bump (major/minor/patch)
        # 3. Update package.json versions
        # 4. Generate CHANGELOG.md
        # 5. Publish to npm
        # 6. Create GitHub release
        # 7. Create git tag

        # Exit code 1 = error, Exit code 0 = success (released or no release needed)
        npx semantic-release

    - name: Release Summary
      if: always()
      run: |
        echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.semantic.outcome }}" == "success" ]; then
          echo "✅ Semantic release completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "Check the [releases page](https://github.com/${{ github.repository }}/releases) for details" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Semantic release failed" >> $GITHUB_STEP_SUMMARY
          echo "Check the logs above for error details" >> $GITHUB_STEP_SUMMARY
        fi