name: Auto Release (Semantic)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'qwlong/dorval'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build
      run: yarn build
    
    - name: Run tests
      run: yarn test
    
    - name: Release with Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        # Configure npm authentication
        npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

        # Run semantic-release
        # This will:
        # 1. Analyze commits since last release
        # 2. Determine version bump (major/minor/patch)
        # 3. Update package.json versions
        # 4. Generate CHANGELOG.md
        # 5. Publish to npm
        # 6. Create GitHub release
        # 7. Create git tag
        npx semantic-release || echo "No release needed (no releasable commits)"